backend:
  name: auth0
  domain: dev-ksr2itt6dm3dvbvl.us.auth0.com
  client_id: vpFhi2cSjuKU0j58RAmcDTLKqtcaa9q5
  audience: ev-ksr2itt6dm3dvbvl.us.auth0.com/api/v2/
  repo: samunando/testeconstru
  branch: main

media_folder: "src/assets/carrossel"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "TÃ­tulo", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Corpo", name: "body", widget: "markdown" }
